services:
  netzmacht.contao_leaflet_maps.listeners.dca.leaflet:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\LeafletDcaListener
    arguments:
      - '@filesystem'
      - '%netzmacht.contao_leaflet_maps.cache_dir%'

  netzmacht.contao_leaflet_maps.listeners.dca.validator:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\Validator
    arguments:
      - '@translator'

  netzmacht.contao_leaflet_maps.listeners.dca.frontend_integration:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\FrontendIntegrationListener
    arguments:
      - '@translator'

  netzmacht.contao_leaflet_maps.listeners.dca.map:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\MapDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@database_connection'

  netzmacht.contao_leaflet_maps.listeners.dca.control:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\ControlDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@database_connection'
      - '%netzmacht.contao_leaflet_maps.controls%'

  netzmacht.contao_leaflet_maps.listeners.dca.layer:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\LayerDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@database_connection'
      - '@translator'
      - '@netzmacht.contao_leaflet_maps.layer_label_renderer'
      - '%netzmacht.contao_leaflet_maps.layers%'
      - '%netzmacht.contao_leaflet_maps.providers%'
      - '%netzmacht.contao_leaflet_maps.amenities%'

  netzmacht.contao_leaflet_maps.listeners.dca.marker:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\MarkerDcaListener
    arguments:
      - '@database_connection'

  netzmacht.contao_leaflet_maps.listeners.dca.vector:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\VectorDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'

  netzmacht.contao_leaflet_maps.listeners.geo_json_subscriber:
    class: Netzmacht\Contao\Leaflet\Subscriber\GeoJsonSubscriber
    arguments:
      - '%netzmacht.contao_leaflet_maps.feature_model_properties%'
    tags:
      - { name: 'kernel.event_subscriber' }

  netzmacht.contao_leaflet_maps.listeners.hash_subscriber:
    class: Netzmacht\Contao\Leaflet\Subscriber\HashSubscriber
    tags:
      - { name: 'kernel.event_subscriber' }

  netzmacht.contao_leaflet_maps.listeners.load_assets:
    class: Netzmacht\Contao\Leaflet\Listener\LoadAssetsListener
    arguments:
      - '@netzmacht.contao_leaflet_maps.map.assets'
      - '@netzmacht.contao_leaflet_maps.definition.mapper'
      - '@netzmacht.contao_leaflet_maps.libraries'
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.contao_leaflet.get_javascript', method: 'onGetJavascriptEvent' }

  netzmacht.contao_leaflet_maps.listeners.register_libraries:
    class: Netzmacht\Contao\Leaflet\Listener\RegisterLibrariesListener
    arguments:
     - '@netzmacht.contao_leaflet_maps.libraries'
     - '@netzmacht.contao_leaflet_maps.definition.builder'

