services:
  netzmacht.contao_leaflet_maps.listeners.dca.map:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\MapDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@database_connection'

  netzmacht.contao_leaflet_maps.listeners.dca.control:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\ControlDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@database_connection'

  netzmacht.contao_leaflet_maps.listeners.dca.layer:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\LayerDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@database_connection'
      - '@translator'
      - '@netzmacht.contao_leaflet_maps.layer_label_renderer'
      - '%netzmacht.contao_leaflet_maps.layers%'
      - '%netzmacht.contao_leaflet_maps.providers%'
      - '%netzmacht.contao_leaflet_maps.amenities%'

  netzmacht.contao_leaflet_maps.listeners.dca.marker:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\MarkerDcaListener
    arguments:
      - '@database_connection'

  netzmacht.contao_leaflet_maps.listeners.dca.vector:
    class: Netzmacht\Contao\Leaflet\Listener\Dca\VectorDcaListener
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
