services:
  # Filters can be passed to a data request to get only specific data from a layer.
  netzmacht.contao_leaflet.filter.bbox:
    class: Netzmacht\Contao\Leaflet\Filter\BboxFilter
    tags:
      - { name: 'netzmacht.contao_leaflet.filter', alias: 'bbox' }

  netzmacht.contao_leaflet.filter.distance:
    class: Netzmacht\Contao\Leaflet\Filter\DistanceFilter
    tags:
      - { name: 'netzmacht.contao_leaflet.filter', alias: 'distance' }
