leaflet_layer:
  path: /layer/{layerId}
  controller: Netzmacht\Contao\Leaflet\Frontend\Action\LayerDataAction
  defaults:
    _leaflet_scope: page
    _format: geojson
    _scope: frontend
  requirements:
    _format: geojson
    context: \w+
    contextId: \d+
