leaflet_layer:
  path: /leaflet/api/layer/{layerId}
  controller: Netzmacht\Contao\Leaflet\Frontend\Action\LayerDataAction
  defaults:
    _leaflet_scope: page
    _format: geojson
    _scope: frontend
  requirements:
    _format: geojson
    context: \w+
    contextId: \d+

leaflet_backend_about:
  path: /contao/leaflet/about
  controller: Netzmacht\Contao\Leaflet\Backend\Action\AboutAction
  defaults:
    _scope: backend
    _backend_module: leaflet_about
